ci: only linux is supported for electron rn

diff --git a/.github/workflows/test-on-pr.yml b/.github/workflows/test-on-pr.yml
--- a/.github/workflows/test-on-pr.yml
+++ b/.github/workflows/test-on-pr.yml
@@ -62,13 +62,9 @@ jobs:
           exit 1
         shell: cmd
 
+  # Electron tests are only tested for Linux for now
   test-electron:
-    strategy:
-      fail-fast: false
-      matrix:
-        platform: [macos-15, ubuntu-22.04, windows-latest]
-
-    runs-on: ${{ matrix.platform }}
+    runs-on: ubuntu-22.04
     timeout-minutes: 60
     steps:
       - uses: actions/checkout@v4
@@ -76,8 +72,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 18
-      - name: install dependencies (ubuntu only)
-        if: matrix.platform == 'ubuntu-22.04'
+      - name: install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y xvfb
@@ -86,39 +81,38 @@ jobs:
           npm install
           echo "npm run build not executed as we will be running tests against the checked in release artifacts only!"
           npm run _copy-dist-to-test
-      - name: Run electron integration tests in ubuntu
-        if: matrix.platform == 'ubuntu-22.04'
+      - name: Run electron integration tests
         run: |
           npm run _serve-tauri &
           sleep 2
           xvfb-run ./src-electron/node_modules/.bin/electron src-electron/main.js --quit-when-done
 
-      - name: Run electron integration tests in macos
-        if: matrix.platform == 'macos-15'
-        run: |
-          npm run _serve-tauri &
-          sleep 2
-          ./src-electron/node_modules/.bin/electron src-electron/main.js --quit-when-done
+      # - name: Run electron integration tests in macos
+      #   if: matrix.platform == 'macos-15'
+      #   run: |
+      #     npm run _serve-tauri &
+      #     sleep 2
+      #     ./src-electron/node_modules/.bin/electron src-electron/main.js --quit-when-done
 
-      - name: Run electron integration tests in windows
-        if: matrix.platform == 'windows-latest'
-        id: windowsElectronRun
-        run: |
-          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run", "_serve-tauri"
-          Start-Sleep -Seconds 2
-          & ".\src-electron\node_modules\.bin\electron.cmd" "src-electron\main.js" "--quit-when-done" 2>&1 | Tee-Object -FilePath electron-output.txt
-        shell: pwsh
-        continue-on-error: true
+      # - name: Run electron integration tests in windows
+      #   if: matrix.platform == 'windows-latest'
+      #   id: windowsElectronRun
+      #   run: |
+      #     Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run", "_serve-tauri"
+      #     Start-Sleep -Seconds 2
+      #     & ".\src-electron\node_modules\.bin\electron.cmd" "src-electron\main.js" "--quit-when-done" 2>&1 | Tee-Object -FilePath electron-output.txt
+      #   shell: pwsh
+      #   continue-on-error: true
 
-      - name: Print windows electron test output to console
-        if: matrix.platform == 'windows-latest'
-        run: |
-          type electron-output.txt
-        shell: cmd
+      # - name: Print windows electron test output to console
+      #   if: matrix.platform == 'windows-latest'
+      #   run: |
+      #     type electron-output.txt
+      #   shell: cmd
 
-      - name: Fail on electron test runs failed in windows
-        if: matrix.platform == 'windows-latest' && steps.windowsElectronRun.outcome == 'failure'
-        run: |
-          echo "Windows Electron tests failed, marking step as failed"
-          exit 1
-        shell: cmd
+      # - name: Fail on electron test runs failed in windows
+      #   if: matrix.platform == 'windows-latest' && steps.windowsElectronRun.outcome == 'failure'
+      #   run: |
+      #     echo "Windows Electron tests failed, marking step as failed"
+      #     exit 1
+      #   shell: cmd
